### ISSUE TITLE
一些关于solo-ltr识别和鉴定上的一些问题

### ISSUE THREAD

**Issue by duan12345678** [ChenGuangji/BirdsSoloLTRs#2]
老师您好：
在运行您提供的代码过程，我遇到了一些问题无法解决，因此萌生的打扰您的想法。以下是我遇到的一些问题：
1.LTR序列的识别的问题
文章中及代码中均提到RepBase library和LTR-harvest 构建LTR的文库文件，您觉得如何添加物种repeatmodeler能否可以实现更好更完整构建LTR文库。因为我发现repeatmodeler鉴定到的lib中ltr的数量会比LTR-harvest略多一些，对此您有更好的建议吗？
2. solo_LTR鉴定的问题：
文章中提到“Finally, we annotated all detected solo-LTRs using RepeatMasker (v4.1.2) with the RepBase library (v.20170127) to identify the sources of solo-LTRs among mammals, reptiles, and birds”，但我在运行数据过程中我鉴定到有3490个Solo_LTR，但其中804个通过该方法被鉴定为DNA,LINE, SINE,simple-repeat等其他转座子类型。我想知道您是否也遇到相同的问题，针对这部分类型鉴定出现异常的solo-LTR您是如何处理的呢？这是否是由于LTR鉴定识别不完整导致的呢？我该如何改进这些问题呢？
3. paired-solod的TSD鉴定的问题
老师在上传的github（https://github.com/ChenGuangji/BirdsSoloLTRs）中TSD中输入文件是否是上游步骤中生成的mafft.identity.out.paired.20k.85.txt文件
  此致
敬礼

**Comment by ChenGuangji** [comment]
> 老师您好： 在运行您提供的代码过程，我遇到了一些问题无法解决，因此萌生的打扰您的想法。以下是我遇到的一些问题： 1.LTR序列的识别的问题 文章中及代码中均提到RepBase library和LTR-harvest 构建LTR的文库文件，您觉得如何添加物种repeatmodeler能否可以实现更好更完整构建LTR文库。因为我发现repeatmodeler鉴定到的lib中ltr的数量会比LTR-harvest略多一些，对此您有更好的建议吗？ 2. solo_LTR鉴定的问题： 文章中提到“Finally, we annotated all detected solo-LTRs using RepeatMasker (v4.1.2) with the RepBase library (v.20170127) to identify the sources of solo-LTRs among mammals, reptiles, and birds”，但我在运行数据过程中我鉴定到有3490个Solo_LTR，但其中804个通过该方法被鉴定为DNA,LINE, SINE,simple-repeat等其他转座子类型。我想知道您是否也遇到相同的问题，针对这部分类型鉴定出现异常的solo-LTR您是如何处理的呢？这是否是由于LTR鉴定识别不完整导致的呢？我该如何改进这些问题呢？ 3. paired-solod的TSD鉴定的问题 老师在上传的github（[https://github.com/ChenGuangji/BirdsSoloLTRs）中TSD中输入文件是否是上游步骤中生成的mafft.identity.out.paired.20k.85.txt文件](https://github.com/ChenGuangji/BirdsSoloLTRs%EF%BC%89%E4%B8%ADTSD%E4%B8%AD%E8%BE%93%E5%85%A5%E6%96%87%E4%BB%B6%E6%98%AF%E5%90%A6%E6%98%AF%E4%B8%8A%E6%B8%B8%E6%AD%A5%E9%AA%A4%E4%B8%AD%E7%94%9F%E6%88%90%E7%9A%84mafft.identity.out.paired.20k.85.txt%E6%96%87%E4%BB%B6) 此致 敬礼

For more other native speakers to understand, I will respond in English:

1. As you may know, LTR-harvest is used to obtain the complete LTR transposon (5' LTR-viral_coding-3' LTR) and to determine the boundaries of its LTR region. This is a major reason why its results are fewer compared to RepeatMasker. If you want to incorporate the results from RepeatModeler, I personally recommend taking the union with RepeatMasker first, and then intersecting with LTR-harvest. I hope this approach works for you.

2. Yes, this is indeed a recognition issue caused by short sequences, which should be classified as "not properly identified yet".

3. Yes, the input file for the TSD identification section is “mafft.identity.out.paired.20k.85.txt”. Given the substantial computational resources required and the fact that there is no significant difference in the results with other parameters, only the results with 20k & 85% were used in TSD identification.

I hope this clarifies things for you. If you have any further questions or need additional information, please let me know.
