### ISSUE TITLE
A question related to the result of  Step9-mark the ltr into paired-LTRs or solo-LTRs

### ISSUE THREAD

**Issue by Xuuuurj** [ChenGuangji/BirdsSoloLTRs#3]
Hello Dr. Chen,

After completing this step, I obtained an output. Should I filter out the paired-l2 results, before running the subsequent TSD-checking? Can you provide some guidance on how to handle this?

I look forward to your valuable advice. Thank you very much for your help!

Best regards,
Rongjing

**Comment by ChenGuangji** [comment]
Hi, Rongjing,

Thanks for trying this.

Considering the removal process of transposons would lead to the target site duplications (TSDs) being imperfect and generating sequence diversity (Fedoroff 2012), it might cause the specific boundaries of TSDs and LTRs to not be so clear (Ji and DeWoody 2016). To address this, I not only checked the target site duplications (TSDs) in the proximal 10 bp upstream and downstream for the paired-LTRs (intact LTRs) and solo-LTRs as employed in (Peona, Blom et al. 2022), but also extended the flanking region into 15 bp and 20 bp. 

It means I didn't filter any "paired-LTRs (intact LTRs)" in "TSD-checking" step. This is a quite strict condition, which would reduce both the false positives and true positives, due to the long-term evolutionary force that might make this short residual trace more unclear.

So, I would like to suggest you try to check the TSDs for all your LTRs, not only the paired-LTRs, but also the solo-LTRs to solidify your conclusions.

Best,
Guangji

**Comment by Xuuuurj** [comment]
Hi Guangji,

Thank you very much for your detailed explanation and helpful suggestions.

I really appreciate the insight you’ve provided. I will certainly follow your advice and recheck all my LTRs to ensure a more robust analysis.

Thanks again for your valuable advice. I will give this a try.
Wishing you an early happy New Year and all the best.

Best regards,
Rongjing
